// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdczytDanych.entities;

#nullable disable

namespace OdczytDanych.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220914121726_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OdczytDanych.entities.Temperatury", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("CzyGrzanieZalaczone")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataPomiaru")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("TemperaturaGleby")
                        .HasColumnType("float");

                    b.Property<float>("TemperaturaPowietrza")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("temperaturies");
                });
#pragma warning restore 612, 618
        }
    }
}
